# Generated by Django 4.2.2 on 2023-06-08 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('monthly_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('refund_on_exit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposits', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan', models.DecimalField(decimal_places=2, max_digits=10)),
                ('share_holding', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch.branch')),
            ],
        ),
    ]
