# Generated by Django 4.2.2 on 2023-06-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_member_wish_to_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='wish_to_deposit',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
    ]
