# Generated by Django 4.2.2 on 2023-06-14 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_alter_branch_id_alter_branch_manager'),
        ('member', '0003_alter_member_wish_to_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='branch.branch'),
        ),
    ]
