# Generated by Django 4.2.2 on 2023-06-16 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_alter_member_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='user',
            new_name='active_user',
        ),
        migrations.AddField(
            model_name='member',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
