# Generated by Django 4.2.2 on 2023-06-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('refund_on_exit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dividend', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pay_off_period_of_dividend', models.IntegerField()),
                ('loan_interest', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan_interest_period', models.IntegerField()),
                ('service_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_fee_period', models.IntegerField()),
            ],
        ),
    ]
