# Generated by Django 4.2.2 on 2023-06-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_controller_dividend_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controller',
            old_name='refund_on_exit',
            new_name='refund_on_exit_monthly_deposit',
        ),
        migrations.AddField(
            model_name='controller',
            name='loan_monthly_salary_ratio_limit',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
        ),
        migrations.AddField(
            model_name='controller',
            name='loan_share_holding_ratio_limit',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
        ),
    ]
