# Generated by Django 4.2.2 on 2023-06-25 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_rename_user_member_active_user_member_position'),
        ('accounts', '0003_alter_cashbookentry_date_alter_cashbookentry_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbookentry',
            name='fund_type',
            field=models.CharField(choices=[('OPENING BALANCE', 'Opening_Balance'), ('CLOSING BALANCE', 'Closing_Balance'), ('INTEREST', 'Interest'), ('DIVIDEND', 'Dividend'), ('SALARY', 'Salary'), ('DEPOSIT', 'Deposit'), ('ADJUSTMENT', 'Adjustment'), ('CHEQUE', 'Cheque'), ('SERVICE_FEE', 'Service Fee'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('ask_loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('allotted_loan_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('number_of_installments', models.IntegerField(default=120)),
                ('allotted_to_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='member.member')),
            ],
        ),
    ]
