# Generated by Django 4.2.2 on 2023-06-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_cashbookentry_fund_type_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbookentry',
            name='shares_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cashbookentry',
            name='fund_type',
            field=models.CharField(choices=[('OPENING BALANCE', 'Opening_Balance'), ('CLOSING BALANCE', 'Closing_Balance'), ('INTEREST', 'Interest'), ('DIVIDEND', 'Dividend'), ('SALARY', 'Salary'), ('DEPOSIT', 'Deposit'), ('ADJUSTMENT', 'Adjustment'), ('CHEQUE', 'Cheque'), ('SERVICE_FEE', 'Service Fee'), ('OTHER', 'Other'), ('LOAN', 'Loan'), ('SHARES', 'Shares')], max_length=20),
        ),
    ]
