# Generated by Django 4.2.2 on 2023-07-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_cashbookentry_shares_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbookentry',
            name='remittance_posted',
            field=models.BooleanField(default=False),
        ),
    ]
