# Generated by Django 4.2.2 on 2023-06-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='branch',
            name='manager',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
